version: "2"
checks:
  method-lines:
    config:
      threshold: 40
plugins:
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - HACK
        - XXX
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_paths:
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - docs/*
  - profiling/*
